/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskSpikeRouteImport } from './routes/ask-spike'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as PointsRouteImport } from './routes/points'
import { Route as DigestsIndexRouteImport } from './routes/digests/index'
import { Route as DigestsDayRouteImport } from './routes/digests/$day'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSplatRouteImport } from './routes/journal/$'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsDayRouteImport } from './routes/reports/$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskSpikeRoute = AskSpikeRouteImport.update({
  id: '/ask-spike',
  path: '/ask-spike',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestsIndexRoute = DigestsIndexRouteImport.update({
  id: '/digests/',
  path: '/digests/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestsDayRoute = DigestsDayRouteImport.update({
  id: '/digests/$day',
  path: '/digests/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSplatRoute = JournalSplatRouteImport.update({
  id: '/journal/$',
  path: '/journal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDayRoute = ReportsDayRouteImport.update({
  id: '/reports/$day',
  path: '/reports/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-spike': typeof AskSpikeRoute
  '/blocks': typeof BlocksRoute
  '/points': typeof PointsRoute
  '/digests/$day': typeof DigestsDayRoute
  '/docs/$': typeof DocsSplatRoute
  '/journal/$': typeof JournalSplatRoute
  '/reports/$day': typeof ReportsDayRoute
  '/digests/': typeof DigestsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-spike': typeof AskSpikeRoute
  '/blocks': typeof BlocksRoute
  '/points': typeof PointsRoute
  '/digests/$day': typeof DigestsDayRoute
  '/docs/$': typeof DocsSplatRoute
  '/journal/$': typeof JournalSplatRoute
  '/reports/$day': typeof ReportsDayRoute
  '/digests': typeof DigestsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-spike': typeof AskSpikeRoute
  '/blocks': typeof BlocksRoute
  '/points': typeof PointsRoute
  '/digests/$day': typeof DigestsDayRoute
  '/docs/$': typeof DocsSplatRoute
  '/journal/$': typeof JournalSplatRoute
  '/reports/$day': typeof ReportsDayRoute
  '/digests/': typeof DigestsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-spike'
    | '/blocks'
    | '/points'
    | '/digests/$day'
    | '/docs/$'
    | '/journal/$'
    | '/reports/$day'
    | '/digests/'
    | '/docs/'
    | '/journal/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-spike'
    | '/blocks'
    | '/points'
    | '/digests/$day'
    | '/docs/$'
    | '/journal/$'
    | '/reports/$day'
    | '/digests'
    | '/docs'
    | '/journal'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/ask-spike'
    | '/blocks'
    | '/points'
    | '/digests/$day'
    | '/docs/$'
    | '/journal/$'
    | '/reports/$day'
    | '/digests/'
    | '/docs/'
    | '/journal/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskSpikeRoute: typeof AskSpikeRoute
  BlocksRoute: typeof BlocksRoute
  PointsRoute: typeof PointsRoute
  DigestsDayRoute: typeof DigestsDayRoute
  DocsSplatRoute: typeof DocsSplatRoute
  JournalSplatRoute: typeof JournalSplatRoute
  ReportsDayRoute: typeof ReportsDayRoute
  DigestsIndexRoute: typeof DigestsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-spike': {
      id: '/ask-spike'
      path: '/ask-spike'
      fullPath: '/ask-spike'
      preLoaderRoute: typeof AskSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digests/': {
      id: '/digests/'
      path: '/digests'
      fullPath: '/digests/'
      preLoaderRoute: typeof DigestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digests/$day': {
      id: '/digests/$day'
      path: '/digests/$day'
      fullPath: '/digests/$day'
      preLoaderRoute: typeof DigestsDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$': {
      id: '/journal/$'
      path: '/journal/$'
      fullPath: '/journal/$'
      preLoaderRoute: typeof JournalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$day': {
      id: '/reports/$day'
      path: '/reports/$day'
      fullPath: '/reports/$day'
      preLoaderRoute: typeof ReportsDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskSpikeRoute: AskSpikeRoute,
  BlocksRoute: BlocksRoute,
  PointsRoute: PointsRoute,
  DigestsDayRoute: DigestsDayRoute,
  DocsSplatRoute: DocsSplatRoute,
  JournalSplatRoute: JournalSplatRoute,
  ReportsDayRoute: ReportsDayRoute,
  DigestsIndexRoute: DigestsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
