/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as ForgesRouteImport } from './routes/forges'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs.$id'
import { Route as ApiJobsIdEventsRouteImport } from './routes/api/jobs.$id.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgesRoute = ForgesRouteImport.update({
  id: '/forges',
  path: '/forges',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsIdEventsRoute = ApiJobsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/forges': typeof ForgesRoute
  '/repos': typeof ReposRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/events': typeof ApiJobsIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/forges': typeof ForgesRoute
  '/repos': typeof ReposRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/events': typeof ApiJobsIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/forges': typeof ForgesRoute
  '/repos': typeof ReposRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/events': typeof ApiJobsIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blueprints'
    | '/forges'
    | '/repos'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blueprints'
    | '/forges'
    | '/repos'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/events'
  id:
    | '__root__'
    | '/'
    | '/blueprints'
    | '/forges'
    | '/repos'
    | '/api/jobs'
    | '/api/jobs/$id'
    | '/api/jobs/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ForgesRoute: typeof ForgesRoute
  ReposRoute: typeof ReposRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forges': {
      id: '/forges'
      path: '/forges'
      fullPath: '/forges'
      preLoaderRoute: typeof ForgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$id/events': {
      id: '/api/jobs/$id/events'
      path: '/events'
      fullPath: '/api/jobs/$id/events'
      preLoaderRoute: typeof ApiJobsIdEventsRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
  }
}

interface ApiJobsIdRouteChildren {
  ApiJobsIdEventsRoute: typeof ApiJobsIdEventsRoute
}

const ApiJobsIdRouteChildren: ApiJobsIdRouteChildren = {
  ApiJobsIdEventsRoute: ApiJobsIdEventsRoute,
}

const ApiJobsIdRouteWithChildren = ApiJobsIdRoute._addFileChildren(
  ApiJobsIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsIdRoute: typeof ApiJobsIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsIdRoute: ApiJobsIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintsRoute: BlueprintsRoute,
  ForgesRoute: ForgesRoute,
  ReposRoute: ReposRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
