/**
 * Render/patch DOC-PROTOCOL architecture-tier docs from the index.
 *
 * Contract with humans and agents:
 *   - frontmatter and the managed regions (component-map, interfaces) are MACHINE-OWNED,
 *     regenerated by `accio sync`, marked by <!-- accio:begin/end --> comments
 *   - everything outside the regions is human/agent-owned prose and preserved byte-for-byte
 *   - aliases are curated in the manifest; the doc frontmatter mirrors them (sync unions
 *     doc-frontmatter aliases back into the manifest, so editing either place works)
 *
 * Headings are an API (DOC-PROTOCOL retrieval contract): `## Component Map` and
 * `## Interfaces & Contracts` verbatim, one row/section per answer.
 */

import { ATTR_DEPTH, type IdxFeature, type IdxComponent, type IdxOpRef } from "./index-store.ts";
import type { Op } from "./spec.ts";

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

export type DocMeta = { feRev: string; date: string; specVersion: string; specUrl: string };

// ---------------------------------------------------------------- frontmatter

const yamlList = (xs: string[]) =>
  xs.length ? `[${xs.map(x => /[^\w\-./{}]/.test(x) ? JSON.stringify(x) : x).join(", ")}]` : "[]";

function renderFrontmatter(f: IdxFeature, meta: DocMeta): string {
  const L = ["---"];
  L.push(`id: ${f.id}`);
  L.push(`tier: architecture`);
  L.push(`feature_name: ${JSON.stringify(f.name)}`);
  L.push(`aliases: ${yamlList(f.aliases)}`);
  if (f.type === "feature") L.push(`product_doc: ./product.md`);
  L.push(`entry_routes: ${yamlList(f.entry_routes)}`);
  L.push("core_files:");
  for (const c of f.core_files) L.push(`  - ${c}`);
  L.push(`last_verified: ${meta.feRev}`);
  L.push(`last_verified_date: ${meta.date}`);
  L.push("---");
  return L.join("\n");
}

/** minimal frontmatter reader — only what sync needs back out of an existing doc */
export function readAliases(doc: string): string[] {
  const m = doc.match(/^---\n[\s\S]*?\naliases:\s*\[([^\]]*)\][\s\S]*?\n---/);
  if (!m || !m[1].trim()) return [];
  return m[1].split(",").map(s => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
}

// ---------------------------------------------------------------- regions

const BEGIN = (name: string) => `<!-- accio:begin ${name} -->`;
const END = (name: string) => `<!-- accio:end ${name} -->`;

const TYPE_RANK = ["Route", "UI page", "UI component", "Hook", "Store", "API module", "Lib", "Module", "Curated group"];
function typeOfFile(file: string): string {
  if (/^src\/routes\//.test(file)) return "Route";
  if (/^src\/pages\/.*index\.tsx$/.test(file)) return "UI page";
  if (/\/use[A-Z][^/]*Store\.ts$|^src\/stores\//.test(file)) return "Store";
  if (/^src\/http\//.test(file)) return "API module";
  if (/\/(hooks\/|use-)[^/]*$/.test(file) || /\/use[A-Z][^/]*\.tsx?$/.test(file)) return "Hook";
  if (/^src\/lib\//.test(file)) return "Lib";
  if (/\.tsx$/.test(file)) return "UI component";
  return "Module";
}

const shortOps = (ops: IdxOpRef[], max = 4) => {
  const direct = ops.filter(o => o.dist <= ATTR_DEPTH);
  const shown = direct.slice(0, max).map(o => `\`${o.key.replace(/^~/, "")}\`${o.key.startsWith("~") ? " _(method inferred)_" : ""}`);
  if (direct.length > max) shown.push(`+${direct.length - max} more`);
  return shown.join("<br>") || "—";
};

function renderComponentMap(f: IdxFeature): string {
  const L: string[] = [];
  L.push(`## Component Map`);
  L.push("");
  L.push(`<!-- GENERATED by \`accio sync\` from the frontend at ${"`"}${f.core_files[0] ?? "src"}${"`"} — do not edit inside this region. -->`);
  L.push("");
  // curated rows first, then approximate execution order: route → page → component → hook → data
  const rowType = (c: IdxComponent) => c.curated ? "Curated group" : typeOfFile(c.files[0] ?? "");
  const rows = [...f.components].sort((a, b) =>
    Number(b.curated) - Number(a.curated)
    || TYPE_RANK.indexOf(rowType(a)) - TYPE_RANK.indexOf(rowType(b))
    || (a.files[0] ?? "").localeCompare(b.files[0] ?? ""));
  if (!rows.length) {
    L.push("_No components with API calls found — either the feature is pure UI, or its `core_files` in the manifest are wrong. Check both before believing either._");
  } else {
    L.push("| Component | Type | Trigger | Calls / API | File |");
    L.push("| --- | --- | --- | --- | --- |");
    for (const c of rows.slice(0, 40)) {
      const file = c.files[0] ?? "—";
      const type = rowType(c);
      const trigger = c.curated ? "—"
        : /^src\/routes\//.test(file) && f.entry_routes.length ? `Route \`${f.entry_routes[0]}\`` : "—";
      const label = c.curated && c.does ? `**\`${c.slug}\`** — ${esc(c.does)}` : `\`${c.slug}\``;
      L.push(`| ${label} | ${type} | ${trigger} | ${shortOps(c.ops)} | \`${esc(file)}\` |`);
    }
    if (rows.length > 40) L.push("", `_…and ${rows.length - 40} more files with calls — see \`accio list --in ${f.id}\`._`);
  }
  const indirect = f.ops.filter(o => o.dist > ATTR_DEPTH);
  if (indirect.length) {
    L.push("");
    L.push(`**Fan-out beyond this feature's contract** _(${indirect.length} ops reached only at >${ATTR_DEPTH} import hops — shared-client traffic, not this feature's own calls)_:`);
    L.push(indirect.slice(0, 8).map(o => `\`${o.key.replace(/^~/, "")}\``).join(" · ") + (indirect.length > 8 ? ` · +${indirect.length - 8}` : ""));
  }
  return L.join("\n");
}

function renderInterfaces(f: IdxFeature, opsByKey: Map<string, Op>): string {
  const L: string[] = [];
  L.push(`## Interfaces & Contracts`);
  L.push("");
  L.push(`<!-- GENERATED by \`accio sync\` from the OpenAPI spec — do not edit inside this region. -->`);
  L.push("");
  const direct = f.ops.filter(o => o.dist <= ATTR_DEPTH);
  if (!direct.length) { L.push("_This feature's code reaches no backend operations._"); return L.join("\n"); }
  L.push(`Endpoints this feature's code calls (≤${ATTR_DEPTH} import hops from its own files):`);
  L.push("");
  for (const o of direct) {
    const key = o.key.replace(/^~/, "");
    const op = opsByKey.get(key);
    L.push(`### \`${key}\`${o.key.startsWith("~") ? " _(method inferred from spec — path literal only)_" : ""}`);
    L.push("");
    if (op?.summary) L.push(op.summary + (op.deprecated ? "  **(deprecated)**" : ""));
    if (op) {
      L.push(`- **Auth:** ${op.auth.length ? op.auth.join(", ") : "_not declared in spec_"}`);
      for (const where of ["path", "query"] as const) {
        const ps = op.params.filter(x => x.in === where);
        if (ps.length) L.push(`- **${where}:** ${ps.map(x => `\`${x.name}\` ${x.type}${x.required ? " **req**" : ""}`).join(" · ")}`);
      }
      if (op.bodySchema) {
        const fields = op.body.slice(0, 10).map(x => `\`${x.name}\`${x.required ? "*" : ""}`).join(", ");
        L.push(`- **Body:** \`${op.bodySchema}\`${fields ? ` — ${fields}${op.body.length > 10 ? ", …" : ""} (* = required)` : ""}`);
      }
      const ok = op.responses.filter(r => r.code.startsWith("2"));
      const err = op.responses.filter(r => !r.code.startsWith("2")).map(r => r.code);
      for (const r of ok) L.push(`- **${r.code}:** \`${r.schema ?? "—"}\``);
      if (err.length) L.push(`- **Errors:** ${err.join(", ")}`);
    } else {
      L.push(`- _no longer in the published spec — flagged by \`accio audit\`_`);
    }
    L.push(`- **Called from:** ${o.sites.slice(0, 3).map(s => `\`${s}\``).join(", ")}${o.dist > 1 ? `  _(${o.dist} hops)_` : ""}`);
    L.push("");
  }
  return L.join("\n").trimEnd();
}

// ---------------------------------------------------------------- assembly

function skeleton(f: IdxFeature): string {
  return [
    "",
    `# ${f.name} — Architecture`,
    "",
    `> **TL;DR:** _one sentence on the shape of the implementation — curated, write me._`,
    "",
    BEGIN("component-map"), "", END("component-map"),
    "",
    BEGIN("interfaces"), "", END("interfaces"),
    "",
    "<!-- Curated sections below (State & Data, Failure Modes, Gaps / Tech Debt, sequence",
    "     diagrams). accio never touches anything outside its regions. -->",
    "",
  ].join("\n");
}

function patchRegion(doc: string, name: string, content: string): string {
  const b = doc.indexOf(BEGIN(name)), e = doc.indexOf(END(name));
  if (b < 0 || e < 0 || e < b) {
    // region lost — reinsert before the curated-sections comment or at the end
    return doc.trimEnd() + `\n\n${BEGIN(name)}\n${content}\n${END(name)}\n`;
  }
  return doc.slice(0, b + BEGIN(name).length) + "\n" + content + "\n" + doc.slice(e);
}

export function renderArchDoc(
  f: IdxFeature, opsByKey: Map<string, Op>, meta: DocMeta, existing: string | null,
): string {
  let body: string;
  if (existing) {
    const fmEnd = existing.match(/^---\n[\s\S]*?\n---/);
    body = fmEnd ? existing.slice(fmEnd[0].length) : existing;
  } else {
    body = skeleton(f);
  }
  body = patchRegion(body, "component-map", renderComponentMap(f));
  body = patchRegion(body, "interfaces", renderInterfaces(f, opsByKey));
  return renderFrontmatter(f, meta) + body.replace(/\s*$/, "\n");
}
