/**
 * Doc-tier stamps — how product.md and arch.md say which code they describe, and the one
 * rule that keeps the two tiers aligned.
 *
 * Both tiers carry `last_verified: <branch>@<sha>`. The product tier is re-verified by a
 * doc subagent and stamped at the FE rev it read. The arch tier is regenerated by
 * `accio sync` on every run, so until 2026-09-01 it was stamped with whatever rev the
 * sync happened to see — 19 of 20 features ended up with tiers that disagreed for no
 * reason a reader could tell apart from real drift.
 *
 * The rule now: the arch stamp FOLLOWS the product stamp unless the feature actually
 * changed since the product tier was verified — its core files diffed, or an endpoint it
 * owns changed in the spec. Only then does the arch stamp move to the current rev, and
 * that mismatch IS the staleness signal `accio audit` and `accio stale` report. A product
 * re-run stamps both tiers at the same rev and closes the gap.
 */

export type Stamp = { rev: string; sha: string; date?: string };

const STAMP_RE = (key: string) => new RegExp(`^${key}:\\s*(\\S+)\\s*$`, "m");
const DATE_RE = (key: string) => new RegExp(`^${key}_date:\\s*(\\S+)\\s*$`, "m");

/** `last_verified` (or `last_verified_be`) out of a doc's frontmatter; null when absent */
export function readStamp(doc: string | null | undefined, key = "last_verified"): Stamp | null {
  if (!doc) return null;
  const fm = doc.match(/^---\n([\s\S]*?)\n---/)?.[1];
  if (!fm) return null;
  const rev = fm.match(STAMP_RE(key))?.[1];
  if (!rev) return null;
  const sha = rev.match(/(?:^|@)([0-9a-f]{7,40})$/)?.[1];
  if (!sha) return null;
  return { rev, sha, date: fm.match(DATE_RE(key))?.[1] };
}

/** The machine-owned regions of a doc, concatenated — what "the generated content changed" compares */
export function regionsOf(doc: string): string {
  return [...doc.matchAll(/<!-- accio:begin (\S+) -->([\s\S]*?)<!-- accio:end \1 -->/g)]
    .map(m => `${m[1]}\n${(m[2] ?? "").trim()}`)
    .join("\n\n");
}

export type StampReason =
  | "new"            // no arch doc yet
  | "no-product"     // feature has no product tier to follow
  | "tree-behind"    // the FE checkout is older than the docs and the feature changed — keep the newer stamp
  | "undecidable"    // git could not diff (unknown sha) — keep what is there
  | "core-changed"   // FE core files moved since the product tier was verified
  | "spec-changed"   // an endpoint this feature owns changed in the spec this sync
  | "aligned";       // nothing changed — arch follows product

export type StampDecision = { rev: string; date: string; reason: StampReason };

/**
 * `coreChangedSinceProduct` is the diff of the feature's core files from the product stamp
 * to the newest rev we can see: HEAD normally, or the existing arch stamp when the shared
 * checkout is older than the docs (`treeBehind`) — two commits diff fine without a
 * checkout, so a behind tree can still ALIGN a stamp; it just can never ADVANCE one.
 */
export function decideArchStamp(input: {
  existingArch: string | null;
  product: string | null;
  current: { rev: string; date: string };
  coreChangedSinceProduct: boolean | null;
  specChanged: boolean;
  /** HEAD is a strict ancestor of the stamp already on the arch doc */
  treeBehind: boolean;
  /** the product stamp is a strict descendant of the arch stamp — a product run re-read newer code */
  productAhead?: boolean;
}): StampDecision {
  const arch = readStamp(input.existingArch);
  const product = readStamp(input.product);
  const keep = (reason: StampReason): StampDecision =>
    arch ? { rev: arch.rev, date: arch.date ?? input.current.date, reason } : { ...input.current, reason };
  const advance = (reason: StampReason): StampDecision =>
    input.treeBehind ? keep("tree-behind") : { ...input.current, reason };

  if (!input.existingArch) return { ...input.current, reason: "new" };
  if (!product) return advance("no-product");
  // A product run is a full re-read of the code at its rev; when that rev is newer than the
  // arch stamp, the arch tier can only follow — whatever HEAD or the spec says this sync.
  if (input.productAhead) return { rev: product.rev, date: product.date ?? input.current.date, reason: "aligned" };
  if (input.specChanged) return advance("spec-changed");
  if (input.coreChangedSinceProduct === null) return keep("undecidable");
  if (input.coreChangedSinceProduct) return advance("core-changed");
  return { rev: product.rev, date: product.date ?? input.current.date, reason: "aligned" };
}

/** Rewrite only `last_verified` / `last_verified_date` in a doc's frontmatter — body untouched */
export function restamp(doc: string, rev: string, date: string): string {
  const fm = doc.match(/^---\n[\s\S]*?\n---/);
  if (!fm) return doc;
  const next = fm[0]
    .replace(/^last_verified:.*$/m, `last_verified: ${rev}`)
    .replace(/^last_verified_date:.*$/m, `last_verified_date: ${date}`);
  return next + doc.slice(fm[0].length);
}

// ---------------------------------------------------------------- git

async function git(repo: string, args: string[]): Promise<{ code: number; out: string }> {
  const p = Bun.spawn(["git", "-C", repo, ...args], { stdout: "pipe", stderr: "ignore" });
  const out = await new Response(p.stdout).text();
  return { code: await p.exited, out: out.trim() };
}

/** files under `paths` that differ between two revs; null when git cannot answer */
export async function gitDiffNames(repo: string, from: string, to: string, paths: string[]): Promise<string[] | null> {
  if (!paths.length) return [];
  const r = await git(repo, ["diff", "--name-only", `${from}..${to}`, "--", ...paths]);
  if (r.code !== 0) return null;
  return r.out ? r.out.split("\n").filter(Boolean) : [];
}

/** true when `a` is an ancestor of `b` (or equal); null when either rev is unknown */
export async function gitIsAncestor(repo: string, a: string, b: string): Promise<boolean | null> {
  const r = await git(repo, ["merge-base", "--is-ancestor", a, b]);
  return r.code === 0 ? true : r.code === 1 ? false : null;
}

export async function gitShortSha(repo: string, rev = "HEAD"): Promise<string | null> {
  const r = await git(repo, ["rev-parse", "--short", rev]);
  return r.code === 0 ? r.out : null;
}
